### ISSUE TITLE
load_all_requirements turns run_exports into a list

### ISSUE THREAD

**Issue by minrk** [prefix-dev/rattler-build-conda-compat#73]
`run_exports` may be a list, or hte actual run_exports dict of the form:

```yaml
run_exports:
  weak:
    - list
  strong:
    - list2
```

but `load_all_requirements` casts this to a length 1 list:

```python
[ {"weak": [...], "strong": ...} ]
```

and doesn't visit conditional items. I'm not sure if this is meant to concatenate all `weak`, `strong`, etc. in a single list or preserve the categories, but at least the conda-smithy code that consumes this seems to expect a flat list.
